using System.Data;
using FluentMigrator;
using FluentMigrator.Legacy.MigratorDotNet;

namespace Urdms.Dmp.Database.Migrations
{
    [Migration(20110906154800)]
    public class CreateSocioEconomicObjective : MigratorDotNetMigration
    {

        #region Constants
        private const string InsertSql = @"INSERT [SocioEconomicObjective]
SELECT '810101','Air Force'
UNION SELECT '810102','Army'
UNION SELECT '810103','Command, Control and Communications'
UNION SELECT '810104','Emerging Defence Technologies'
UNION SELECT '810105','Intelligence'
UNION SELECT '810106','Logistics'
UNION SELECT '810107','National Security'
UNION SELECT '810108','Navy'
UNION SELECT '810109','Personnel'
UNION SELECT '810199','Defence not elsewhere classified'
UNION SELECT '820101','Hardwood Plantations'
UNION SELECT '820102','Harvesting and Transport of Forest Products'
UNION SELECT '820103','Integration of Farm and Forestry'
UNION SELECT '820104','Native Forests'
UNION SELECT '820105','Softwood Plantations'
UNION SELECT '820199','Forestry not elsewhere classified'
UNION SELECT '820201','Almonds'
UNION SELECT '820202','Berry Fruit (excl. Kiwifruit)'
UNION SELECT '820203','Citrus Fruit'
UNION SELECT '820204','Hops'
UNION SELECT '820205','Kiwifruit'
UNION SELECT '820206','Macadamias'
UNION SELECT '820207','Mushrooms and Truffles'
UNION SELECT '820208','Olives'
UNION SELECT '820209','Ornamentals, Natives, Flowers and Nursery Plants'
UNION SELECT '820210','Pome Fruit, Pip Fruit'
UNION SELECT '820211','Stone Fruit'
UNION SELECT '820212','Table Grapes'
UNION SELECT '820213','Tree Nuts (excl. Almonds and Macadamias)'
UNION SELECT '820214','Tropical Fruit'
UNION SELECT '820215','Vegetables'
UNION SELECT '820299','Horticultural Crops not elsewhere classified'
UNION SELECT '820301','Cotton'
UNION SELECT '820302','Essential Oil Crops (e.g. Tea Tree, Eucalyptus, Lavender, Peppermint, Boronia, Sandalwood)'
UNION SELECT '820303','Plant Extract Crops (e.g. Pyrethrum, Jojoba)'
UNION SELECT '820304','Sugar'
UNION SELECT '820305','Tobacco'
UNION SELECT '820306','Wine Grapes'
UNION SELECT '820399','Industrial Crops not elsewhere classified'
UNION SELECT '820401','Maize'
UNION SELECT '820402','Rice'
UNION SELECT '820403','Safflower Seed'
UNION SELECT '820404','Sorghum'
UNION SELECT '820405','Soybeans'
UNION SELECT '820499','Summer Grains and Oilseeds not elsewhere classified'
UNION SELECT '820501','Barley'
UNION SELECT '820502','Canola'
UNION SELECT '820503','Grain Legumes'
UNION SELECT '820504','Linseed'
UNION SELECT '820505','Lupins'
UNION SELECT '820506','Oats'
UNION SELECT '820507','Wheat'
UNION SELECT '820599','Winter Grains and Oilseeds not elsewhere classified'
UNION SELECT '820601','Cotton Lint and Cotton Seed'
UNION SELECT '820602','Fresh Fruits and Vegetables (Post Harvest)'
UNION SELECT '820603','Sugar Cane (Cut for Crushing)'
UNION SELECT '820604','Tobacco Leaf'
UNION SELECT '820605','Unprocessed Grains'
UNION SELECT '820606','Unprocessed Industrial Crops (excl. Sugar, Tobacco and Cotton)'
UNION SELECT '820607','Unprocessed Oilseeds'
UNION SELECT '820699','Harvesting and Packing of Plant Products not elsewhere classified'
UNION SELECT '829801','Management of Gaseous Waste from Plant Production (excl. Greenhouse Gases)'
UNION SELECT '829802','Management of Greenhouse Gas Emissions from Plant Production'
UNION SELECT '829803','Management of Liquid Waste from Plant Production (excl. Water)'
UNION SELECT '829804','Management of Solid Waste from Plant Production'
UNION SELECT '829805','Management of Water Consumption by Plant Production'
UNION SELECT '829899','Environmentally Sustainable Plant Production not elsewhere classified'
UNION SELECT '829901','Forest Product Traceability and Quality Assurance'
UNION SELECT '829902','Plant Product Traceability and Quality Assurance (excl. Forest Products)'
UNION SELECT '829999','Plant Production and Plant Primary Products not elsewhere classified'
UNION SELECT '830101','Aquaculture Crustaceans (excl. Rock Lobster and Prawns)'
UNION SELECT '830102','Aquaculture Fin Fish (excl. Tuna)'
UNION SELECT '830103','Aquaculture Molluscs (excl. Oysters)'
UNION SELECT '830104','Aquaculture Oysters'
UNION SELECT '830105','Aquaculture Prawns'
UNION SELECT '830106','Aquaculture Rock Lobster'
UNION SELECT '830107','Aquaculture Tuna'
UNION SELECT '830199','Fisheries - Aquaculture not elsewhere classified'
UNION SELECT '830201','Fisheries – Recreational'
UNION SELECT '830202','Wild Caught Crustaceans (excl. Rock Lobster and Prawns)'
UNION SELECT '830203','Wild Caught Edible Molluscs'
UNION SELECT '830204','Wild Caught Fin Fish (excl. Tuna)'
UNION SELECT '830205','Wild Caught Prawns'
UNION SELECT '830206','Wild Caught Rock Lobster'
UNION SELECT '830207','Wild Caught Tuna'
UNION SELECT '830299','Fisheries- Wild Caught not elsewhere classified'
UNION SELECT '830301','Beef Cattle'
UNION SELECT '830302','Dairy Cattle'
UNION SELECT '830303','Deer'
UNION SELECT '830304','Goats'
UNION SELECT '830305','Game Livestock (e.g. Kangaroos, Wallabies, Camels, Buffaloes, Possums)'
UNION SELECT '830306','Horses'
UNION SELECT '830307','Minor Livestock (e.g. Alpacas, Ostriches, Crocodiles, Farmed Rabbits)'
UNION SELECT '830308','Pigs'
UNION SELECT '830309','Poultry'
UNION SELECT '830310','Sheep - Meat'
UNION SELECT '830311','Sheep - Wool'
UNION SELECT '830399','Livestock Raising not elsewhere classified'
UNION SELECT '830401','Browse Crops'
UNION SELECT '830402','Lucerne'
UNION SELECT '830403','Native and Residual Pastures'
UNION SELECT '830404','Non-Cereal Crops for Hay'
UNION SELECT '830405','Non-Cereal Crops for Silage/Green Feed'
UNION SELECT '830406','Sown Pastures (excl. Lucerne)'
UNION SELECT '830499','Pasture, Browse and Fodder Crops not elsewhere classified'
UNION SELECT '830501','Eggs'
UNION SELECT '830502','Honey'
UNION SELECT '830503','Live Animals'
UNION SELECT '830504','Pearls'
UNION SELECT '830505','Raw Wool'
UNION SELECT '830506','Unprocessed or Minimally Processed Fish'
UNION SELECT '830507','Unprocessed or Minimally Processed Milk'
UNION SELECT '830599','Primary Animal Products not elsewhere classified'
UNION SELECT '839801','Management of Gaseous Waste from Animal Production (excl. Greenhouse Gases)'
UNION SELECT '839802','Management of Greenhouse Gas Emissions from Animal Production'
UNION SELECT '839803','Management of Liquid Waste from Animal Production (excl. Water)'
UNION SELECT '839804','Management of Solid Waste from Animal Production'
UNION SELECT '839805','Management of Water Consumption by Animal Production'
UNION SELECT '839899','Environmentally Sustainable Animal Production not elsewhere classified'
UNION SELECT '839901','Animal Welfare'
UNION SELECT '839902','Fish Product Traceability and Quality Assurance'
UNION SELECT '839903','Livestock Product Traceability and Quality Assurance'
UNION SELECT '839999','Animal Production and Animal Primary Products not elsewhere classified'
UNION SELECT '840101','Aluminium Ore Exploration'
UNION SELECT '840102','Copper Ore Exploration'
UNION SELECT '840103','Diamond Exploration'
UNION SELECT '840104','Iron Ore Exploration'
UNION SELECT '840105','Precious (Noble) Metal Ore Exploration'
UNION SELECT '840106','Stone and Clay Exploration'
UNION SELECT '840107','Titanium Minerals, Zircon, and Rare Earth Metal Ore (e.g. Monazite) Exploration'
UNION SELECT '840108','Zinc Ore Exploration'
UNION SELECT '840199','Mineral Exploration not elsewhere classified'
UNION SELECT '840201','Mining and Extraction of Aluminium Ores'
UNION SELECT '840202','Mining and Extraction of Copper Ores'
UNION SELECT '840203','Mining and Extraction of Diamonds'
UNION SELECT '840204','Mining and Extraction of Iron Ores'
UNION SELECT '840205','Mining and Extraction of Precious (Noble) Metal Ores'
UNION SELECT '840206','Mining and Extraction of Stone and Clay'
UNION SELECT '840207','Mining and Extraction of Titanium Minerals, Zircon, and Rare Earth Metal Ores (e.g. Monazite)'
UNION SELECT '840208','Mining and Extraction of Zinc Ores'
UNION SELECT '840299','Primary Mining and Extraction of Mineral Resources not elsewhere classified'
UNION SELECT '840301','Alumina Production'
UNION SELECT '840302','Beneficiation of Bauxite and Aluminium Ores (excl. Alumina Production)'
UNION SELECT '840303','Beneficiation or Dressing of Iron Ores'
UNION SELECT '840304','Beneficiation or Dressing of Non-Metallic Minerals (incl. Diamonds)'
UNION SELECT '840305','Concentrating Processes of Base Metal Ores (excl. Aluminium and Iron Ores)'
UNION SELECT '840306','Production of Unrefined Precious Metal Ingots and Concentrates'
UNION SELECT '840399','First Stage Treatment of Ores and Minerals not elsewhere classified'
UNION SELECT '849801','Management of Gaseous Waste from Mineral Resource Activities (excl. Greenhouse Gases)'
UNION SELECT '849802','Management of Greenhouse Gas Emissions from Mineral Resource Activities'
UNION SELECT '849803','Management of Liquid Waste from Mineral Resource Activities (excl. Water)'
UNION SELECT '849804','Management of Solid Waste from Mineral Resource Activities'
UNION SELECT '849805','Management of Water Consumption by Mineral Resource Activities'
UNION SELECT '849899','Environmentally Sustainable Mineral Resource Activities not elsewhere classified'
UNION SELECT '849999','Mineral Resources (excl. Energy Resources) not elsewhere classified'
UNION SELECT '850101','Coal Exploration'
UNION SELECT '850102','Geothermal Exploration'
UNION SELECT '850103','Oil and Gas Exploration'
UNION SELECT '850104','Oil Shale and Tar Sands Exploration'
UNION SELECT '850105','Uranium Exploration'
UNION SELECT '850199','Energy Exploration not elsewhere classified'
UNION SELECT '850201','Coal Mining and Extraction'
UNION SELECT '850202','Geothermal Energy Extraction'
UNION SELECT '850203','Oil and Gas Extraction'
UNION SELECT '850204','Oil Shale and Tar Sands Mining and Extraction'
UNION SELECT '850205','Uranium Mining and Extraction'
UNION SELECT '850299','Mining and Extraction of Energy Resources not elsewhere classified'
UNION SELECT '850301','Hydrogen Production from Fossil Fuels'
UNION SELECT '850302','Hydrogen Production from Nuclear Energy'
UNION SELECT '850303','Hydrogen Production from Renewable Energy'
UNION SELECT '850304','Oil and Gas Refining'
UNION SELECT '850305','Preparation of Black Coal'
UNION SELECT '850306','Preparation of Brown Coal (Lignite)'
UNION SELECT '850307','Preparation of Oil Shale and Tar Sands'
UNION SELECT '850308','Preparation of Uranium'
UNION SELECT '850309','Production of Biofuels (Biomass)'
UNION SELECT '850399','Preparation and Production of Energy Sources not elsewhere classified'
UNION SELECT '850401','Fuel Cells (excl. Solid Oxide)'
UNION SELECT '850402','Hydrogen-based Energy Systems (incl. Internal Hydrogen Combustion Engines)'
UNION SELECT '850403','Nuclear Energy'
UNION SELECT '850404','Solid Oxide Fuel Cells'
UNION SELECT '850405','Transformation of Black Coal into Electricity'
UNION SELECT '850406','Transformation of Brown Coal (Lignite) into Electricity'
UNION SELECT '850407','Transformation of Coal into Gaseous Fuels'
UNION SELECT '850408','Transformation of Coal into Liquid Fuels'
UNION SELECT '850409','Transformation of Gas into Electricity'
UNION SELECT '850410','Transformation of Gas into Liquid Fuels'
UNION SELECT '850499','Energy Transformation not elsewhere classified'
UNION SELECT '850501','Biofuel (Biomass) Energy'
UNION SELECT '850502','Geothermal Energy'
UNION SELECT '850503','Hydro-Electric Energy'
UNION SELECT '850504','Solar-Photovoltaic Energy'
UNION SELECT '850505','Solar-Thermal Electric Energy'
UNION SELECT '850506','Solar-Thermal Energy'
UNION SELECT '850507','Tidal Energy'
UNION SELECT '850508','Wave Energy'
UNION SELECT '850509','Wind Energy'
UNION SELECT '850599','Renewable Energy not elsewhere classified'
UNION SELECT '850601','Energy Services and Utilities'
UNION SELECT '850602','Energy Storage (excl. Hydrogen)'
UNION SELECT '850603','Energy Systems Analysis'
UNION SELECT '850604','Energy Transmission and Distribution (excl. Hydrogen)'
UNION SELECT '850605','Hydrogen Distribution'
UNION SELECT '850606','Hydrogen Storage'
UNION SELECT '850699','Energy Storage, Distribution and Supply not elsewhere classified'
UNION SELECT '850701','Commercial Energy Conservation and Efficiency'
UNION SELECT '850702','Energy Conservation and Efficiency in Transport'
UNION SELECT '850703','Industrial Energy Conservation and Efficiency'
UNION SELECT '850704','Residential Energy Conservation and Efficiency'
UNION SELECT '850799','Energy Conservation and Efficiency not elsewhere classified'
UNION SELECT '859801','Management of Gaseous Waste from Energy Activities (excl. Greenhouse Gases)'
UNION SELECT '859802','Management of Greenhouse Gas Emissions from Electricity Generation'
UNION SELECT '859803','Management of Greenhouse Gas Emissions from Energy Activities (excl. Electricity Generation)'
UNION SELECT '859804','Management of Liquid Waste from Energy Activities (excl. Water)'
UNION SELECT '859805','Management of Solid Waste from Energy Activities'
UNION SELECT '859806','Management of Water Consumption by Energy Activities'
UNION SELECT '859899','Environmentally Sustainable Energy Activities not elsewhere classified'
UNION SELECT '859999','Energy not elsewhere classified'
UNION SELECT '860101','Bakery Products'
UNION SELECT '860102','Beverages (excl. Fruit Juices)'
UNION SELECT '860103','Carcass Meat (incl. Fish and Seafood)'
UNION SELECT '860104','Flour Mill and Cereal Food'
UNION SELECT '860105','Nutraceuticals and Functional Foods'
UNION SELECT '860106','Oils and Fats (incl. Margarines)'
UNION SELECT '860107','Processed Fish and Seafood Products'
UNION SELECT '860108','Processed Fruit and Vegetable Products (incl. Fruit Juices)'
UNION SELECT '860109','Processed Meat Products'
UNION SELECT '860110','Soy Products'
UNION SELECT '860111','Sugar and Confectionery Products'
UNION SELECT '860199','Processed Food Products and Beverages (excl. Dairy Products) not elsewhere classified'
UNION SELECT '860201','Butter and Milk-Derived Fats and Oils (excl. Cream)'
UNION SELECT '860202','Casein'
UNION SELECT '860203','Cheese'
UNION SELECT '860204','Processed Milk and Cream (incl. Powder, Evaporated and Condensed)'
UNION SELECT '860205','Whey'
UNION SELECT '860299','Dairy Products not elsewhere classified'
UNION SELECT '860301','Essential Oils (e.g. Tea Tree, Eucalyptus, Lavender, Peppermint, Boronia, Sandalwood)'
UNION SELECT '860302','Organic Fertilisers'
UNION SELECT '860303','Plant Extracts (e.g. Pyrethrum, Alkaloids, Jojoba Oil)'
UNION SELECT '860304','Prepared Animal Feed'
UNION SELECT '860399','Processed Non-Food Agricultural Products (excl. Wood, Paper and Fibre) not elsewhere classified'
UNION SELECT '860401','Clothing'
UNION SELECT '860402','Cotton Ginning'
UNION SELECT '860403','Natural Fibres, Yarns and Fabrics'
UNION SELECT '860404','Non-Fabric Textiles (e.g. Felt)'
UNION SELECT '860405','Processed Skins, Leather and Leather Products'
UNION SELECT '860406','Synthetic Fibres, Yarns and Fabrics'
UNION SELECT '860407','Wool Scouring and Top Making'
UNION SELECT '860499','Leather Products, Fibre Processing and Textiles not elsewhere classified'
UNION SELECT '860501','Paper Products (incl. Coated Paper)'
UNION SELECT '860502','Printing and Publishing Processes'
UNION SELECT '860503','Pulp and Paper'
UNION SELECT '860504','Reconstituted Timber Products (e.g. Chipboard, Particleboard)'
UNION SELECT '860505','Wood Sawing and Veneer'
UNION SELECT '860599','Wood, Wood Products and Paper not elsewhere classified'
UNION SELECT '860601','Industrial Gases'
UNION SELECT '860602','Inorganic Industrial Chemicals'
UNION SELECT '860603','Lubricants'
UNION SELECT '860604','Organic Industrial Chemicals (excl. Resins, Rubber and Plastics)'
UNION SELECT '860605','Paints'
UNION SELECT '860606','Plastics in Primary Forms'
UNION SELECT '860607','Plastic Products (incl. Construction Materials)'
UNION SELECT '860608','Rubber and Synthetic Resins'
UNION SELECT '860609','Soaps and Cosmetics'
UNION SELECT '860699','Industrial Chemicals and Related Products not elsewhere classified'
UNION SELECT '860701','Animal Protection Chemicals'
UNION SELECT '860702','Chemical Fertilisers'
UNION SELECT '860703','Crop Protection Chemicals'
UNION SELECT '860799','Agricultural Chemicals not elsewhere classified'
UNION SELECT '860801','Human Biological Preventatives (e.g. Vaccines)'
UNION SELECT '860802','Human Diagnostics'
UNION SELECT '860803','Human Pharmaceutical Treatments (e.g. Antibiotics)'
UNION SELECT '860899','Human Pharmaceutical Products not elsewhere classified'
UNION SELECT '860901','Veterinary Biological Preventatives (e.g. Vaccines)'
UNION SELECT '860902','Veterinary Diagnostics'
UNION SELECT '860903','Veterinary Pharmaceutical Treatments (e.g. Antibiotics)'
UNION SELECT '860999','Veterinary Pharmaceutical Products not elsewhere classified'
UNION SELECT '861001','Cement and Concrete Materials'
UNION SELECT '861002','Ceramics'
UNION SELECT '861003','Clay Products'
UNION SELECT '861004','Plaster and Plaster Products'
UNION SELECT '861005','Structural Glass and Glass Products'
UNION SELECT '861099','Ceramics, Glass and Industrial Mineral Products not elsewhere classified'
UNION SELECT '861101','Basic Aluminium Products'
UNION SELECT '861102','Basic Copper Products'
UNION SELECT '861103','Basic Iron and Steel Products'
UNION SELECT '861104','Basic Precious Metal Products'
UNION SELECT '861105','Basic Zinc Products'
UNION SELECT '861199','Basic Metal Products (incl. Smelting, Rolling, Drawing and Extruding) not elsewhere classified'
UNION SELECT '861201','Coated Metal and Metal-Coated Products'
UNION SELECT '861202','Machined Metal Products'
UNION SELECT '861203','Metal Castings'
UNION SELECT '861204','Semi-Finished Metal Products'
UNION SELECT '861205','Sheet Metal Products'
UNION SELECT '861206','Structural Metal Products'
UNION SELECT '861299','Fabricated Metal Products not elsewhere classified'
UNION SELECT '861301','Aerospace Equipment'
UNION SELECT '861302','Automotive Equipment'
UNION SELECT '861303','Nautical Equipment (excl. Yachts)'
UNION SELECT '861304','Rail Equipment'
UNION SELECT '861305','Yachts'
UNION SELECT '861399','Transport Equipment not elsewhere classified'
UNION SELECT '861401','Agricultural Machinery and Equipment'
UNION SELECT '861402','Appliances and Electrical Machinery and Equipment'
UNION SELECT '861403','Industrial Machinery and Equipment'
UNION SELECT '861404','Mining Machinery and Equipment'
UNION SELECT '861499','Machinery and Equipment not elsewhere classified'
UNION SELECT '861501','Industrial Instruments'
UNION SELECT '861502','Medical Instruments'
UNION SELECT '861503','Scientific Instruments'
UNION SELECT '861599','Instrumentation not elsewhere classified'
UNION SELECT '861601','Computer and Electronic Office Equipment'
UNION SELECT '861602','Consumer Electronic Equipment (excl. Communication Equipment)'
UNION SELECT '861603','Integrated Circuits and Devices'
UNION SELECT '861604','Integrated Systems'
UNION SELECT '861605','Processor Modules'
UNION SELECT '861606','Satellite Navigation Equipment'
UNION SELECT '861699','Computer Hardware and Electronic Equipment not elsewhere classified'
UNION SELECT '861701','Network Infrastructure Equipment'
UNION SELECT '861702','Telemetry Equipment'
UNION SELECT '861703','Voice and Data Equipment'
UNION SELECT '861799','Communication Equipment not elsewhere classified'
UNION SELECT '869801','Management of Gaseous Waste from Manufacturing Activities (excl. Greenhouse Gases)'
UNION SELECT '869802','Management of Greenhouse Gas Emissions from Manufacturing Activities'
UNION SELECT '869803','Management of Liquid Waste from Manufacturing Activities (excl. Water)'
UNION SELECT '869804','Management of Solid Waste from Manufacturing Activities'
UNION SELECT '869805','Management of Water Consumption by Manufacturing Activities'
UNION SELECT '869899','Environmentally Sustainable Manufacturing not elsewhere classified'
UNION SELECT '869901','Furniture'
UNION SELECT '869999','Manufacturing not elsewhere classified'
UNION SELECT '870101','Civil Construction Planning'
UNION SELECT '870102','Commercial Construction Planning'
UNION SELECT '870103','Regional Planning'
UNION SELECT '870104','Residential Construction Planning'
UNION SELECT '870105','Urban Planning'
UNION SELECT '870199','Construction Planning not elsewhere classified'
UNION SELECT '870201','Civil Construction Design'
UNION SELECT '870202','Commercial Construction Design'
UNION SELECT '870203','Industrial Construction Design'
UNION SELECT '870204','Residential Construction Design'
UNION SELECT '870299','Construction Design not elsewhere classified'
UNION SELECT '870301','Cement and Concrete Materials'
UNION SELECT '870302','Metals (e.g. Composites, Coatings, Bonding)'
UNION SELECT '870303','Polymeric Materials (e.g. Paints)'
UNION SELECT '870304','Stone, Ceramics and Clay Materials'
UNION SELECT '870305','Timber Materials'
UNION SELECT '870399','Construction Materials Performance and Processes not elsewhere classified'
UNION SELECT '870401','Civil Construction Processes'
UNION SELECT '870402','Commercial Construction Processes'
UNION SELECT '870403','Industrial Construction Processes'
UNION SELECT '870404','Residential Construction Processes'
UNION SELECT '870499','Construction Processes not elsewhere classified'
UNION SELECT '870501','Civil Building Management and Services'
UNION SELECT '870502','Commercial Building Management and Services'
UNION SELECT '870503','Residential Building Management and Services'
UNION SELECT '870599','Building Management and Services not elsewhere classified'
UNION SELECT '879801','Management of Gaseous Waste from Construction Activities (excl. Greenhouse Gases)'
UNION SELECT '879802','Management of Greenhouse Gas Emissions from Construction Activities'
UNION SELECT '879803','Management of Liquid Waste from Construction Activities (excl. Water)'
UNION SELECT '879804','Management of Solid Waste from Construction Activities'
UNION SELECT '879805','Management of Water Consumption by Construction Activities'
UNION SELECT '879899','Environmentally Sustainable Construction not elsewhere classified'
UNION SELECT '879999','Construction not elsewhere classified'
UNION SELECT '880101','Rail Freight'
UNION SELECT '880102','Rail Infrastructure and Networks'
UNION SELECT '880103','Rail Passenger Movements'
UNION SELECT '880104','Rail Safety'
UNION SELECT '880105','Road Freight'
UNION SELECT '880106','Road Infrastructure and Networks'
UNION SELECT '880107','Road Passenger Movements (excl. Public Transport)'
UNION SELECT '880108','Road Public Transport'
UNION SELECT '880109','Road Safety'
UNION SELECT '880199','Ground Transport not elsewhere classified'
UNION SELECT '880201','Coastal Sea Freight Transport'
UNION SELECT '880202','International Sea Freight Transport (excl. Live Animal Transport)'
UNION SELECT '880203','International Sea Transport of Live Animals'
UNION SELECT '880204','Passenger Water Transport'
UNION SELECT '880205','Port Infrastructure and Management'
UNION SELECT '880206','Water Safety'
UNION SELECT '880299','Water Transport not elsewhere classified'
UNION SELECT '880301','Air Freight'
UNION SELECT '880302','Air Passenger Transport'
UNION SELECT '880303','Air Safety'
UNION SELECT '880304','Air Terminal Infrastructure and Management'
UNION SELECT '880305','Space Transport'
UNION SELECT '880399','Aerospace Transport not elsewhere classified'
UNION SELECT '889801','Management of Gaseous Waste from Transport Activities (excl. Greenhouse Gases)'
UNION SELECT '889802','Management of Greenhouse Gas Emissions from Transport Activities'
UNION SELECT '889803','Management of Liquid Waste from Transport Activities (excl. Water)'
UNION SELECT '889804','Management of Noise and Vibration from Transport Activities'
UNION SELECT '889805','Management of Solid Waste from Transport Activities'
UNION SELECT '889806','Management of Water Consumption by Transport Activities'
UNION SELECT '889899','Environmentally Sustainable Transport not elsewhere classified'
UNION SELECT '889901','Intermodal Materials Handling'
UNION SELECT '889902','Multimodal Transport'
UNION SELECT '889903','Pipeline Transport'
UNION SELECT '889904','Postal and Package Services (incl. Courier Services)'
UNION SELECT '889999','Transport not elsewhere classified'
UNION SELECT '890101','Fixed Line Data Networks and Services'
UNION SELECT '890102','Fixed Line Telephone Networks and Services'
UNION SELECT '890103','Mobile Data Networks and Services'
UNION SELECT '890104','Mobile Telephone Networks and Services'
UNION SELECT '890105','Satellite Communication Networks and Services'
UNION SELECT '890106','Videoconference Services'
UNION SELECT '890199','Communication Networks and Services not elsewhere classified'
UNION SELECT '890201','Application Software Packages (excl. Computer Games)'
UNION SELECT '890202','Application Tools and System Utilities'
UNION SELECT '890203','Computer Gaming Software'
UNION SELECT '890204','Computer Time Leasing, Sharing and Renting Services'
UNION SELECT '890205','Information Processing Services (incl. Data Entry and Capture)'
UNION SELECT '890206','Internet Hosting Services (incl. Application Hosting Services)'
UNION SELECT '890299','Computer Software and Services not elsewhere classified'
UNION SELECT '890301','Electronic Information Storage and Retrieval Services'
UNION SELECT '890302','Library and Archival Services'
UNION SELECT '890303','News Collection Services'
UNION SELECT '890399','Information Services not elsewhere classified'
UNION SELECT '890401','Animation and Computer Generated Imagery Services'
UNION SELECT '890402','Film and Video Services (excl. Animation and Computer Generated Imagery)'
UNION SELECT '890403','Internet Broadcasting'
UNION SELECT '890404','Publishing and Print Services (incl. Internet Publishing)'
UNION SELECT '890405','Radio and Television Broadcasting'
UNION SELECT '890499','Media Services not elsewhere classified'
UNION SELECT '899801','Management of Greenhouse Gas Emissions from Information and Communication Services'
UNION SELECT '899802','Management of Solid Waste from Information and Communication Services'
UNION SELECT '899803','Management of Water Consumption by Information and Communication Services'
UNION SELECT '899899','Environmentally Sustainable Information and Communication Services not elsewhere classified'
UNION SELECT '899999','Information and Communication Services not elsewhere classified'
UNION SELECT '900101','Finance Services'
UNION SELECT '900102','Investment Services (excl. Superannuation)'
UNION SELECT '900103','Superannuation and Insurance Services'
UNION SELECT '900199','Financial Services not elsewhere classified'
UNION SELECT '900201','Administration and Business Support Services'
UNION SELECT '900202','Professional, Scientific and Technical Services'
UNION SELECT '900203','Property Services (incl. Security)'
UNION SELECT '900204','Wholesale and Retail Trade'
UNION SELECT '900299','Property, Business Support Services and Trade not elsewhere classified'
UNION SELECT '900301','Economic Issues in Tourism'
UNION SELECT '900302','Socio-Cultural Issues in Tourism'
UNION SELECT '900303','Tourism Infrastructure Development'
UNION SELECT '900399','Tourism not elsewhere classified'
UNION SELECT '900401','Waste Management Services'
UNION SELECT '900402','Waste Recycling Services'
UNION SELECT '900403','Water Recycling Services (incl. Sewage and Greywater)'
UNION SELECT '900404','Water Services and Utilities'
UNION SELECT '900499','Water and Waste Services not elsewhere classified'
UNION SELECT '909801','Management of Gaseous Waste from Commercial Services and Tourism (excl. Greenhouse Gases)'
UNION SELECT '909802','Management of Greenhouse Gas Emissions from Commercial Services and Tourism'
UNION SELECT '909803','Management of Liquid Waste from Commercial Services and Tourism (excl. Water)'
UNION SELECT '909804','Management of Solid Waste from Commercial Services and Tourism'
UNION SELECT '909805','Management of Water Consumption by Commercial Services and Tourism'
UNION SELECT '909899','Environmentally Sustainable Commercial Services and Tourism not elsewhere classified'
UNION SELECT '909901','Hospitality Services'
UNION SELECT '909902','Recreational Services'
UNION SELECT '909999','Commercial Services and Tourism not elsewhere classified'
UNION SELECT '910101','Balance of Payments'
UNION SELECT '910102','Demography'
UNION SELECT '910103','Economic Growth'
UNION SELECT '910104','Exchange Rates'
UNION SELECT '910105','Fiscal Policy'
UNION SELECT '910106','Income Distribution'
UNION SELECT '910107','Macro Labour Market Issues'
UNION SELECT '910108','Monetary Policy'
UNION SELECT '910109','Savings and Investments'
UNION SELECT '910110','Taxation'
UNION SELECT '910199','Macroeconomics not elsewhere classified'
UNION SELECT '910201','Consumption'
UNION SELECT '910202','Human Capital Issues'
UNION SELECT '910203','Industrial Organisations'
UNION SELECT '910204','Industry Costs and Structure'
UNION SELECT '910205','Industry Policy'
UNION SELECT '910206','Market-Based Mechanisms'
UNION SELECT '910207','Microeconomic Effects of Taxation'
UNION SELECT '910208','Micro Labour Market Issues'
UNION SELECT '910209','Preference, Behaviour and Welfare'
UNION SELECT '910210','Production'
UNION SELECT '910211','Supply and Demand'
UNION SELECT '910299','Microeconomics not elsewhere classified'
UNION SELECT '910301','International Agreements on Trade'
UNION SELECT '910302','Trade Assistance and Protection'
UNION SELECT '910303','Trade Policy'
UNION SELECT '910399','International Trade not elsewhere classified'
UNION SELECT '910401','Industrial Relations'
UNION SELECT '910402','Management'
UNION SELECT '910403','Marketing'
UNION SELECT '910404','Productivity (excl. Public Sector)'
UNION SELECT '910405','Public Sector Productivity'
UNION SELECT '910406','Technological and Organisational Innovation'
UNION SELECT '910499','Management and Productivity not elsewhere classified'
UNION SELECT '910501','Agricultural and Environmental Standards'
UNION SELECT '910502','Defence Standards and Calibrations'
UNION SELECT '910503','Manufacturing Standards and Calibrations'
UNION SELECT '910504','Service Industries Standards and Calibrations'
UNION SELECT '910599','Measurement Standards and Calibration Services not elsewhere classified'
UNION SELECT '919901','Carbon and Emissions Trading'
UNION SELECT '919902','Ecological Economics'
UNION SELECT '919999','Economic Framework not elsewhere classified'
UNION SELECT '920101','Blood Disorders'
UNION SELECT '920102','Cancer and Related Disorders'
UNION SELECT '920103','Cardiovascular System and Diseases'
UNION SELECT '920104','Diabetes'
UNION SELECT '920105','Digestive System Disorders'
UNION SELECT '920106','Endocrine Organs and Diseases (excl. Diabetes)'
UNION SELECT '920107','Hearing, Vision, Speech and Their Disorders'
UNION SELECT '920108','Immune System and Allergy'
UNION SELECT '920109','Infectious Diseases'
UNION SELECT '920110','Inherited Diseases (incl. Gene Therapy)'
UNION SELECT '920111','Nervous System and Disorders'
UNION SELECT '920112','Neurodegenerative Disorders Related to Ageing'
UNION SELECT '920113','Oro-Dental Disorders'
UNION SELECT '920114','Reproductive System and Disorders'
UNION SELECT '920115','Respiratory System and Diseases (incl. Asthma)'
UNION SELECT '920116','Skeletal System and Disorders (incl. Arthritis)'
UNION SELECT '920117','Skin and Related Disorders'
UNION SELECT '920118','Surgical Methods and Procedures'
UNION SELECT '920119','Urogenital System and Disorders'
UNION SELECT '920120','Zoonoses'
UNION SELECT '920199','Clinical Health (Organs, Diseases and Abnormal Conditions) not elsewhere classified'
UNION SELECT '920201','Allied Health Therapies (excl. Mental Health Services)'
UNION SELECT '920202','Carer Health'
UNION SELECT '920203','Diagnostic Methods'
UNION SELECT '920204','Evaluation of Health Outcomes'
UNION SELECT '920205','Health Education and Promotion'
UNION SELECT '920206','Health Policy Economic Outcomes'
UNION SELECT '920207','Health Policy Evaluation'
UNION SELECT '920208','Health Inequalities'
UNION SELECT '920209','Mental Health Services'
UNION SELECT '920210','Nursing'
UNION SELECT '920211','Palliative Care'
UNION SELECT '920299','Health and Support Services not elsewhere classified'
UNION SELECT '920301','Aboriginal and Torres Strait Islander Health - Determinants of Health'
UNION SELECT '920302','Aboriginal and Torres Strait Islander Health - Health Status and Outcomes'
UNION SELECT '920303','Aboriginal and Torres Strait Islander Health - Health System Performance (incl. Effectiveness of Interventions)'
UNION SELECT '920304','Maori Health - Determinants of Health'
UNION SELECT '920305','Maori Health - Health Status and Outcomes'
UNION SELECT '920306','Maori Health - Health System Performance (incl. Effectiveness of Interventions)'
UNION SELECT '920307','Pacific Peoples Health - Determinants Of Health'
UNION SELECT '920308','Pacific Peoples Health - Health Status and Outcomes'
UNION SELECT '920309','Pacific Peoples Health - Health System Performance (incl. Effectiveness of Interventions)'
UNION SELECT '920399','Indigenous Health not elsewhere classified'
UNION SELECT '920401','Behaviour and Health'
UNION SELECT '920402','Dental Health'
UNION SELECT '920403','Disability and Functional Capacity'
UNION SELECT '920404','Disease Distribution and Transmission (incl. Surveillance and Response)'
UNION SELECT '920405','Environmental Health'
UNION SELECT '920406','Food Safety'
UNION SELECT '920407','Health Protection and/or Disaster Response'
UNION SELECT '920408','Health Status (e.g. Indicators of Well-Being)'
UNION SELECT '920409','Injury Control'
UNION SELECT '920410','Mental Health'
UNION SELECT '920411','Nutrition'
UNION SELECT '920412','Preventive Medicine'
UNION SELECT '920413','Social Structure and Health'
UNION SELECT '920414','Substance Abuse'
UNION SELECT '920499','Public Health (excl. Specific Population Health) not elsewhere classified'
UNION SELECT '920501','Child Health'
UNION SELECT '920502','Health Related to Ageing'
UNION SELECT '920503','Health Related to Specific Ethnic Groups'
UNION SELECT '920504','Occupational Health'
UNION SELECT '920505','Mens Health'
UNION SELECT '920506','Rural Health'
UNION SELECT '920507','Womens Health'
UNION SELECT '920599','Specific Population Health (excl. Indigenous Health) not elsewhere classified'
UNION SELECT '929999','Health not elsewhere classified'
UNION SELECT '930101','Learner and Learning Achievement'
UNION SELECT '930102','Learner and Learning Processes'
UNION SELECT '930103','Learner Development'
UNION SELECT '930104','Moral and Social Development (incl. Affect)'
UNION SELECT '930199','Learner and Learning not elsewhere classified'
UNION SELECT '930201','Pedagogy'
UNION SELECT '930202','Teacher and Instructor Development'
UNION SELECT '930203','Teaching and Instruction Technologies'
UNION SELECT '930299','Teaching and Instruction not elsewhere classified'
UNION SELECT '930301','Assessment and Evaluation of Curriculum'
UNION SELECT '930302','Syllabus and Curriculum Development'
UNION SELECT '930399','Curriculum not elsewhere classified'
UNION SELECT '930401','Management and Leadership of Schools/Institutions'
UNION SELECT '930402','School/Institution Community and Environment'
UNION SELECT '930403','School/Institution Policies and Development'
UNION SELECT '930499','School/Institution not elsewhere classified'
UNION SELECT '930501','Education and Training Systems Policies and Development'
UNION SELECT '930502','Management of Education and Training Systems'
UNION SELECT '930503','Resourcing of Education and Training Systems'
UNION SELECT '930599','Education and Training Systems not elsewhere classified'
UNION SELECT '939901','Aboriginal and Torres Strait Islander Education'
UNION SELECT '939902','Education and Training Theory and Methodology'
UNION SELECT '939903','Equity and Access to Education'
UNION SELECT '939904','Gender Aspects of Education'
UNION SELECT '939905','Maori Education'
UNION SELECT '939906','Pacific Peoples Education'
UNION SELECT '939907','Special Needs Education'
UNION SELECT '939908','Workforce Transition and Employment'
UNION SELECT '939999','Education and Training not elsewhere classified'
UNION SELECT '940101','Ability and Disability'
UNION SELECT '940102','Aboriginal and Torres Strait Islander Development and Welfare'
UNION SELECT '940103','Ageing and Older People'
UNION SELECT '940104','Carers’ Development and Welfare'
UNION SELECT '940105','Childrens/Youth Services and Childcare'
UNION SELECT '940106','Citizenship and National Identity'
UNION SELECT '940107','Comparative Structure and Development of Community Services'
UNION SELECT '940108','Distribution of Income and Wealth'
UNION SELECT '940109','Employment Services'
UNION SELECT '940110','Environmental Services'
UNION SELECT '940111','Ethnicity, Multiculturalism and Migrant Development and Welfare'
UNION SELECT '940112','Families and Family Services'
UNION SELECT '940113','Gender and Sexualities'
UNION SELECT '940114','Maori Development and Welfare'
UNION SELECT '940115','Pacific Peoples Development and Welfare'
UNION SELECT '940116','Social Class and Inequalities'
UNION SELECT '940117','Structure, Delivery and Financing of Community Services'
UNION SELECT '940199','Community Service (excl. Work) not elsewhere classified'
UNION SELECT '940201','Civics and Citizenship'
UNION SELECT '940202','Electoral Systems'
UNION SELECT '940203','Political Systems'
UNION SELECT '940204','Public Services Policy Advice and Analysis'
UNION SELECT '940299','Government and Politics not elsewhere classified'
UNION SELECT '940301','Defence and Security Policy'
UNION SELECT '940302','International Aid and Development'
UNION SELECT '940303','International Organisations'
UNION SELECT '940304','International Political Economy (excl. International Trade)'
UNION SELECT '940399','International Relations not elsewhere classified'
UNION SELECT '940401','Civil Justice'
UNION SELECT '940402','Crime Prevention'
UNION SELECT '940403','Criminal Justice'
UNION SELECT '940404','Law Enforcement'
UNION SELECT '940405','Law Reform'
UNION SELECT '940406','Legal Processes'
UNION SELECT '940407','Legislation, Civil and Criminal Codes'
UNION SELECT '940408','Rehabilitation and Correctional Services'
UNION SELECT '940499','Justice and the Law not elsewhere classified'
UNION SELECT '940501','Employment Patterns and Change'
UNION SELECT '940502','Professions and Professionalisation'
UNION SELECT '940503','Time Use, Unpaid Work and Volunteering'
UNION SELECT '940504','Work and Family Responsibilities'
UNION SELECT '940505','Workplace Safety'
UNION SELECT '940599','Work and Institutional Development not elsewhere classified'
UNION SELECT '949999','Law, Politics and Community Services not elsewhere classified'
UNION SELECT '950101','Music'
UNION SELECT '950102','Organised Sports'
UNION SELECT '950103','Recreation'
UNION SELECT '950104','The Creative Arts (incl. Graphics and Craft)'
UNION SELECT '950105','The Performing Arts (incl. Theatre and Dance)'
UNION SELECT '950199','Arts and Leisure not elsewhere classified'
UNION SELECT '950201','Communication Across Languages and Culture'
UNION SELECT '950202','Languages and Literacy'
UNION SELECT '950203','Languages and Literature'
UNION SELECT '950204','The Media'
UNION SELECT '950205','Visual Communication'
UNION SELECT '950299','Communication not elsewhere classified'
UNION SELECT '950301','Ahuatanga Maori (Maori Tradition)'
UNION SELECT '950302','Conserving Aboriginal and Torres Strait Islander Heritage'
UNION SELECT '950303','Conserving Collections and Movable Cultural Heritage'
UNION SELECT '950304','Conserving Intangible Cultural Heritage'
UNION SELECT '950305','Conserving Natural Heritage'
UNION SELECT '950306','Conserving Pacific Peoples Heritage'
UNION SELECT '950307','Conserving the Historic Environment'
UNION SELECT '950308','Matauranga Maori (Maori Knowledge)'
UNION SELECT '950309','Taonga (Maori Artefacts)'
UNION SELECT '950310','Tikanga Maori (Maori Customary Practices)'
UNION SELECT '950311','Wahi Taonga (Maori Places of Significance)'
UNION SELECT '950399','Heritage not elsewhere classified'
UNION SELECT '950401','Bioethics'
UNION SELECT '950402','Business Ethics'
UNION SELECT '950403','Environmental Ethics'
UNION SELECT '950404','Religion and Society'
UNION SELECT '950405','Religious Structures and Ritual'
UNION SELECT '950406','Religious Traditions (excl. Structures and Rituals)'
UNION SELECT '950407','Social Ethics'
UNION SELECT '950408','Technological Ethics'
UNION SELECT '950409','Workplace and Organisational Ethics'
UNION SELECT '950499','Religion and Ethics not elsewhere classified'
UNION SELECT '950501','Understanding Africas Past'
UNION SELECT '950502','Understanding Asias Past'
UNION SELECT '950503','Understanding Australias Past'
UNION SELECT '950504','Understanding Europes Past'
UNION SELECT '950505','Understanding New Zealands Past'
UNION SELECT '950506','Understanding the Past of the Americas'
UNION SELECT '950599','Understanding Past Societies not elsewhere classified'
UNION SELECT '959999','Cultural Understanding not elsewhere classified'
UNION SELECT '960101','Antarctic and Sub-Antarctic Air Quality'
UNION SELECT '960102','Coastal and Estuarine Air Quality'
UNION SELECT '960103','Farmland, Arable Cropland and Permanent Cropland Air Quality'
UNION SELECT '960104','Marine Air Quality'
UNION SELECT '960105','Mining Air Quality'
UNION SELECT '960106','Urban and Industrial Air Quality'
UNION SELECT '960199','Air Quality not elsewhere classified'
UNION SELECT '960201','Atmospheric Composition (incl. Greenhouse Gas Inventory)'
UNION SELECT '960202','Atmospheric Processes and Dynamics'
UNION SELECT '960203','Weather'
UNION SELECT '960299','Atmosphere and Weather not elsewhere classified'
UNION SELECT '960301','Climate Change Adaptation Measures'
UNION SELECT '960302','Climate Change Mitigation Strategies'
UNION SELECT '960303','Climate Change Models'
UNION SELECT '960304','Climate Variability (excl. Social Impacts)'
UNION SELECT '960305','Ecosystem Adaptation to Climate Change'
UNION SELECT '960306','Effects of Climate Change and Variability on Antarctic and Sub-Antarctic Environments (excl. Social Impacts)'
UNION SELECT '960307','Effects of Climate Change and Variability on Australia (excl. Social Impacts)'
UNION SELECT '960308','Effects of Climate Change and Variability on New Zealand (excl. Social Impacts)'
UNION SELECT '960309','Effects of Climate Change and Variability on the South Pacific (excl. Australia and New Zealand) (excl. Social'
UNION SELECT '960310','Global Effects of Climate Change and Variability (excl. Australia, New Zealand, Antarctica and the South Pacific)'
UNION SELECT '960311','Social Impacts of Climate Change and Variability'
UNION SELECT '960399','Climate and Climate Change not elsewhere classified'
UNION SELECT '960401','Border Biosecurity (incl. Quarantine and Inspection)'
UNION SELECT '960402','Control of Animal Pests, Diseases and Exotic Species in Coastal and Estuarine Environments'
UNION SELECT '960403','Control of Animal Pests, Diseases and Exotic Species in Farmland, Arable Cropland and Permanent Cropland'
UNION SELECT '960404','Control of Animal Pests, Diseases and Exotic Species in Forest and Woodlands Environments'
UNION SELECT '960405','Control of Pests, Diseases and Exotic Species at Regional or Larger Scales'
UNION SELECT '960406','Control of Pests, Diseases and Exotic Species in Fresh, Ground and Surface Water Environments'
UNION SELECT '960407','Control of Pests, Diseases and Exotic Species in Marine Environments'
UNION SELECT '960408','Control of Pests, Diseases and Exotic Species in Mining Environments'
UNION SELECT '960409','Control of Pests, Diseases and Exotic Species in Mountain and High Country Environments'
UNION SELECT '960410','Control of Pests, Diseases and Exotic Species in Sparseland, Permanent Grassland and Arid Zone Environments'
UNION SELECT '960411','Control of Pests, Diseases and Exotic Species in Urban and Industrial Environments'
UNION SELECT '960412','Control of Plant Pests, Diseases and Exotic Species in Coastal and Estuarine Environments'
UNION SELECT '960413','Control of Plant Pests, Diseases and Exotic Species in Farmland, Arable Cropland and Permanent Cropland'
UNION SELECT '960414','Control of Plant Pests, Diseases and Exotic Species in Forest and Woodlands Environments'
UNION SELECT '960415','Pre-Border Biosecurity'
UNION SELECT '960499','Control of Pests, Diseases and Exotic Species not elsewhere classified'
UNION SELECT '960501','Ecosystem Assessment and Management of Antarctic and Sub-Antarctic Environments'
UNION SELECT '960502','Ecosystem Assessment and Management of Coastal and Estuarine Environments'
UNION SELECT '960503','Ecosystem Assessment and Management of Farmland, Arable Cropland and Permanent Cropland Environments'
UNION SELECT '960504','Ecosystem Assessment and Management of Forest and Woodlands Environments'
UNION SELECT '960505','Ecosystem Assessment and Management of Fresh, Ground and Surface Water Environments'
UNION SELECT '960506','Ecosystem Assessment and Management of Marine Environments'
UNION SELECT '960507','Ecosystem Assessment and Management of Mining Environments'
UNION SELECT '960508','Ecosystem Assessment and Management of Mountain and High Country Environments'
UNION SELECT '960509','Ecosystem Assessment and Management at Regional or Larger Scales'
UNION SELECT '960510','Ecosystem Assessment and Management of Sparseland, Permanent Grassland and Arid Zone Environments'
UNION SELECT '960511','Ecosystem Assessment and Management of Urban and Industrial Environments'
UNION SELECT '960599','Ecosystem Assessment and Management not elsewhere classified'
UNION SELECT '960601','Economic Incentives for Environmental Protection'
UNION SELECT '960602','Eco-Verification (excl. Environmental Lifecycle Assessment)'
UNION SELECT '960603','Environmental Lifecycle Assessment'
UNION SELECT '960604','Environmental Management Systems'
UNION SELECT '960605','Institutional Arrangements for Environmental Protection'
UNION SELECT '960606','Rights to Environmental and Natural Resources (excl. Water Allocation)'
UNION SELECT '960607','Rural Land Evaluation'
UNION SELECT '960608','Rural Water Evaluation (incl. Water Quality)'
UNION SELECT '960609','Sustainability Indicators'
UNION SELECT '960610','Urban Land Evaluation'
UNION SELECT '960611','Urban Water Evaluation (incl. Water Quality)'
UNION SELECT '960699','Environmental and Natural Resource Evaluation not elsewhere classified'
UNION SELECT '960701','Coastal and Marine Management Policy'
UNION SELECT '960702','Consumption Patterns, Population Issues and the Environment'
UNION SELECT '960703','Environmental Education and Awareness'
UNION SELECT '960704','Land Stewardship'
UNION SELECT '960705','Rural Land Policy'
UNION SELECT '960706','Rural Water Policy'
UNION SELECT '960707','Trade and Environment'
UNION SELECT '960708','Urban Land Policy'
UNION SELECT '960709','Urban Water Policy'
UNION SELECT '960799','Environmental Policy, Legislation and Standards not elsewhere classified'
UNION SELECT '960801','Antarctic and Sub-Antarctic Flora, Fauna and Biodiversity'
UNION SELECT '960802','Coastal and Estuarine Flora, Fauna and Biodiversity'
UNION SELECT '960803','Documentation of Undescribed Flora and Fauna'
UNION SELECT '960804','Farmland, Arable Cropland and Permanent Cropland Flora, Fauna and Biodiversity'
UNION SELECT '960805','Flora, Fauna and Biodiversity at Regional or Larger Scales'
UNION SELECT '960806','Forest and Woodlands Flora, Fauna and Biodiversity'
UNION SELECT '960807','Fresh, Ground and Surface Water Flora, Fauna and Biodiversity'
UNION SELECT '960808','Marine Flora, Fauna and Biodiversity'
UNION SELECT '960809','Mining Flora, Fauna and Biodiversity'
UNION SELECT '960810','Mountain and High Country Flora, Fauna and Biodiversity'
UNION SELECT '960811','Sparseland, Permanent Grassland and Arid Zone Flora, Fauna and Biodiversity'
UNION SELECT '960812','Urban and Industrial Flora, Fauna and Biodiversity'
UNION SELECT '960899','Flora, Fauna and Biodiversity of Environments not elsewhere classified'
UNION SELECT '960901','Antarctic and Sub-Antarctic Land and Water Management'
UNION SELECT '960902','Coastal and Estuarine Land Management'
UNION SELECT '960903','Coastal and Estuarine Water Management'
UNION SELECT '960904','Farmland, Arable Cropland and Permanent Cropland Land Management'
UNION SELECT '960905','Farmland, Arable Cropland and Permanent Cropland Water Management'
UNION SELECT '960906','Forest and Woodlands Land Management'
UNION SELECT '960907','Forest and Woodlands Water Management'
UNION SELECT '960908','Mining Land and Water Management'
UNION SELECT '960909','Mountain and High Country Land and Water Management'
UNION SELECT '960910','Sparseland, Permanent Grassland and Arid Zone Land and Water Management'
UNION SELECT '960911','Urban and Industrial Land Management'
UNION SELECT '960912','Urban and Industrial Water Management'
UNION SELECT '960913','Water Allocation and Quantification'
UNION SELECT '960999','Land and Water Management of Environments not elsewhere classified'
UNION SELECT '961001','Natural Hazards in Antarctic and Sub-Antarctic Environments'
UNION SELECT '961002','Natural Hazards in Coastal and Estuarine Environments'
UNION SELECT '961003','Natural Hazards in Farmland, Arable Cropland and Permanent Cropland Environments'
UNION SELECT '961004','Natural Hazards in Forest and Woodlands Environments'
UNION SELECT '961005','Natural Hazards in Fresh, Ground and Surface Water Environments'
UNION SELECT '961006','Natural Hazards in Marine Environments'
UNION SELECT '961007','Natural Hazards in Mining Environments'
UNION SELECT '961008','Natural Hazards in Mountain and High Country Environments'
UNION SELECT '961009','Natural Hazards in Sparseland, Permanent Grassland and Arid Zone Environments'
UNION SELECT '961010','Natural Hazards in Urban and Industrial Environments'
UNION SELECT '961099','Natural Hazards not elsewhere classified'
UNION SELECT '961101','Physical and Chemical Conditions of Water for Urban and Industrial Use'
UNION SELECT '961102','Physical and Chemical Conditions of Water in Coastal and Estuarine Environments'
UNION SELECT '961103','Physical and Chemical Conditions of Water in Fresh, Ground and Surface Water Environments (excl. Urban and'
UNION SELECT '961104','Physical and Chemical Conditions of Water in Marine Environments'
UNION SELECT '961199','Physical and Chemical Conditions of Water not elsewhere classified'
UNION SELECT '961201','Rehabilitation of Degraded Coastal and Estuarine Environments'
UNION SELECT '961202','Rehabilitation of Degraded Farmland, Arable Cropland and Permanent Cropland Environments'
UNION SELECT '961203','Rehabilitation of Degraded Forest and Woodlands Environments'
UNION SELECT '961204','Rehabilitation of Degraded Fresh, Ground and Surface Water Environments'
UNION SELECT '961205','Rehabilitation of Degraded Mining Environments'
UNION SELECT '961206','Rehabilitation of Degraded Mountain and High Country Environments'
UNION SELECT '961207','Rehabilitation of Degraded Sparseland, Permanent Grassland and Arid Zone Environments'
UNION SELECT '961208','Rehabilitation of Degraded Urban and Industrial Environments'
UNION SELECT '961299','Rehabilitation of Degraded Environments not elsewhere classified'
UNION SELECT '961301','Protected Conservation Areas in Antarctic and Sub-Antarctic Environments'
UNION SELECT '961302','Protected Conservation Areas in Fresh, Ground and Surface Water Environments'
UNION SELECT '961303','Protected Conservation Areas in Marine Environments'
UNION SELECT '961304','Remnant Vegetation and Protected Conservation Areas in Coastal and Estuarine Environments'
UNION SELECT '961305','Remnant Vegetation and Protected Conservation Areas in Farmland, Arable Cropland and Permanent Cropland'
UNION SELECT '961306','Remnant Vegetation and Protected Conservation Areas in Forest and Woodlands Environments'
UNION SELECT '961307','Remnant Vegetation and Protected Conservation Areas in Mountain and High Country Environments'
UNION SELECT '961308','Remnant Vegetation and Protected Conservation Areas at Regional or Larger Scales'
UNION SELECT '961309','Remnant Vegetation and Protected Conservation Areas in Sparseland, Permanent Grassland and Arid Zone'
UNION SELECT '961310','Remnant Vegetation and Protected Conservation Areas in Urban and Industrial Environments'
UNION SELECT '961399','Remnant Vegetation and Protected Conservation Areas not elsewhere classified'
UNION SELECT '961401','Coastal and Estuarine Soils'
UNION SELECT '961402','Farmland, Arable Cropland and Permanent Cropland Soils'
UNION SELECT '961403','Forest and Woodlands Soils'
UNION SELECT '961404','Mining Soils'
UNION SELECT '961405','Mountain and High Country Soils'
UNION SELECT '961406','Sparseland, Permanent Grassland and Arid Zone Soils'
UNION SELECT '961407','Urban and Industrial Soils'
UNION SELECT '961499','Soils not elsewhere classified'
UNION SELECT '969901','Antarctic and Sub-Antarctic Oceanography'
UNION SELECT '969902','Marine Oceanic Processes (excl. Climate Related)'
UNION SELECT '969999','Environment not elsewhere classified'
UNION SELECT '970101','Expanding Knowledge in the Mathematical Sciences'
UNION SELECT '970102','Expanding Knowledge in the Physical Sciences'
UNION SELECT '970103','Expanding Knowledge in the Chemical Sciences'
UNION SELECT '970104','Expanding Knowledge in the Earth Sciences'
UNION SELECT '970105','Expanding Knowledge in the Environmental Sciences'
UNION SELECT '970106','Expanding Knowledge in the Biological Sciences'
UNION SELECT '970107','Expanding Knowledge in the Agricultural and Veterinary Sciences'
UNION SELECT '970108','Expanding Knowledge in the Information and Computing Sciences'
UNION SELECT '970109','Expanding Knowledge in Engineering'
UNION SELECT '970110','Expanding Knowledge in Technology'
UNION SELECT '970111','Expanding Knowledge in the Medical and Health Sciences'
UNION SELECT '970112','Expanding Knowledge in Built Environment and Design'
UNION SELECT '970113','Expanding Knowledge in Education'
UNION SELECT '970114','Expanding Knowledge in Economics'
UNION SELECT '970115','Expanding Knowledge in Commerce, Management, Tourism and Services'
UNION SELECT '970116','Expanding Knowledge through Studies of Human Society'
UNION SELECT '970117','Expanding Knowledge in Psychology and Cognitive Sciences'
UNION SELECT '970118','Expanding Knowledge in Law and Legal Studies'
UNION SELECT '970119','Expanding Knowledge through Studies of the Creative Arts and Writing'
UNION SELECT '970120','Expanding Knowledge in Language, Communication and Culture'
UNION SELECT '970121','Expanding Knowledge in History and Archaeology'
UNION SELECT '970122','Expanding Knowledge in Philosophy and Religious Studies'";
        #endregion

        public override void Up()
        {
            Database.RemoveTable("SocioEconomicResearch");

            Database.AddTable("SocioEconomicObjective",
             new Column("Id", DbType.String, ColumnProperty.PrimaryKey),
             new Column("Name", DbType.String, 1000));

            Database.ExecuteNonQuery(InsertSql);

            Database.AddTable("ProjectSocioEconomicObjective",
                              new Column("Id", DbType.Int32, ColumnProperty.PrimaryKeyWithIdentity),
                              new Column("ProjectId", DbType.Int32),
                              new Column("SocioEconomicObjectiveId", DbType.Int32),
                              new Column("Allocation", DbType.Double, ColumnProperty.NotNull));


        }

        public override void Down()
        {
            Database.RemoveTable("SocioEconomicObjective");
            Database.RemoveTable("ProjectSocioEconomicObjective");

            Database.AddTable("SocioEconomicResearch",
               new Column("Id", DbType.Int32, ColumnProperty.PrimaryKeyWithIdentity),
               new Column("Code", DbType.String, 100, ColumnProperty.NotNull),
               new Column("Allocation", DbType.Double, ColumnProperty.NotNull),
               new Column("[ProjectId]", DbType.Int32, ColumnProperty.NotNull));
        }
    }
}
