//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdms.Dmp.Web.Views.Auth
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using Urdms.Dmp.Web.Pages;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Auth/LogOn.cshtml")]
    public class _Page_Views_Auth_LogOn_cshtml : Urdms.Dmp.Web.Pages.BasePage<Urdms.Dmp.Web.Controllers.LogOnViewModel>
    {
#line hidden

        public _Page_Views_Auth_LogOn_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


  
    PageSettings.Title = "Log In";
    AddScript("jquery.validate.min");
    AddScript("jquery.validate.unobtrusive.min");
    AddStylesheet("Login.css");


WriteLiteral("\r\n<h1>User Login</h1>\r\n\r\n");


Write(Html.ValidationSummary(false, "Login was unsuccessful. Please correct the errors and try again."));

WriteLiteral("\r\n\r\n<p>You need to log in to access this area. Please supply your Curtin network " +
"credentials.</p>\r\n\r\n");


 using (Html.BeginForm())
{

WriteLiteral("    <ol>\r\n        <li>");


       Write(Html.LabelFor(m => m.UserName));

WriteLiteral(" ");


                                       Write(Html.TextBoxFor(m => m.UserName));

WriteLiteral(" ");


                                                                         Write(Html.ValidationMessageFor(m => m.UserName));

WriteLiteral("</li>\r\n        <li>");


       Write(Html.LabelFor(m => m.Password));

WriteLiteral(" ");


                                       Write(Html.PasswordFor(m => m.Password));

WriteLiteral(" ");


                                                                          Write(Html.ValidationMessageFor(m => m.Password));

WriteLiteral("</li>\r\n    </ol>\r\n");



WriteLiteral("    <input type=\"submit\" class=\"submitButton\" value=\"Login\" />\r\n");



WriteLiteral("    <script type=\"text/javascript\">\r\n    <!--\r\n        if (document.getElementByI" +
"d && (u=document.getElementById(\"UserName\"))) {\r\n            u.focus();\r\n       " +
" }\r\n    -->\r\n    </script>\r\n");


}

        }
    }
}
