#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdms.Dmp.Web.FlowForms.Helpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 1 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    using Curtin.Framework.Common.Classes;
    
    #line default
    #line hidden
    
    #line 3 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    using Urdms.Dmp.Web.FlowForms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    public static class HelperDefinitions
    {

public static System.Web.WebPages.HelperResult Header(string heading, IHtmlString instructions = null, string logo = null, string logoAlt = null, IHtmlString legislation = null, IHtmlString copyright = null) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 5 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                                                                          

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\"header\">\r\n");



#line 7 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     if (logo != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"logo\"><img src=\"");



#line 8 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, logo);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" alt=\"");



#line 8 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, logoAlt);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" /></div>\r\n");



#line 9 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <h1>");



#line 10 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h1>\r\n");



#line 11 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     if (legislation != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <p class=\"legislation\">");



#line 12 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, legislation);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 13 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden



#line 14 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     if (instructions != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <div class=\"instructions\">");



#line 15 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, instructions);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 16 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden



#line 17 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     if (copyright != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <p class=\"copyright\">");



#line 18 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, copyright);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 19 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </div>\r\n");



#line 21 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Steps(IList<Step> steps, int current, int maxComplete, bool showLinks, bool stopLinksAtMaxComplete) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 23 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                             

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ol class=\"progress\">\r\n");



#line 25 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     for (int i = 1; i <= steps.Count; i++) {
        var step = steps[i-1];
        var theClass = "";
        if (i < current) {
            theClass = "complete";
        }
        if (i == current) {
            theClass = "current";
        }
        if (i > current) {
            theClass = (i <= maxComplete) ? "incomplete visited" : "incomplete";
        }
        if (!string.IsNullOrWhiteSpace(step.Class)) {
            theClass = string.Format("{0} {1}", theClass, step.Class);
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li class=\"");



#line 40 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, theClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 41 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
             if (showLinks && !string.IsNullOrEmpty(step.Url) && (!stopLinksAtMaxComplete || i <= maxComplete)) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <a href=\"");



#line 42 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, step.Url);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 42 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, step.Name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</a>\r\n");



#line 43 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
            } else {
                
#line default
#line hidden


#line 44 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, step.Name);

#line default
#line hidden


#line 44 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                          
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </li>\r\n");



#line 47 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ol>\r\n");



#line 49 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginSection(bool nested, string heading, string id = null, IHtmlString hint = null, string hintClass = null, bool optional = false, IHtmlString instructions = null, bool omitDl = false, bool hasParent = false) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 51 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                                                                                                                            
    var cssClass = omitDl ? "section noDl" : "section";
    if (!nested) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<fieldset\r\n");



#line 55 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        if (id != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "id=\"");



#line 56 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"\r\n");



#line 57 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "class=\"");



#line 58 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cssClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <legend>");



#line 59 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</legend>\r\n");



#line 60 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        if (instructions != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <div class=\"instructions\">");



#line 61 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, instructions);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 62 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        }
    } else if (!hasParent) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <dt>");



#line 64 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden



#line 64 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                     if (optional) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " <em>(Optional)</em>");



#line 64 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                     }
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<dd ");



#line 65 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
               if (id != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "id=\"");



#line 65 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"");



#line 65 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                     }
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 66 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        if (hint != null){

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <p class=\"hint ");



#line 67 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, hintClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 67 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, hint);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 68 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        }
    }
    if (!omitDl)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<dl ");



#line 72 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
               if (hasParent && id != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "id=\"");



#line 72 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
            WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"");



#line 72 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                  }
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 73 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndSection(bool omitDl, bool nested, bool hasParent) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 76 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                              
    if (!omitDl) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dl>\r\n");



#line 79 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }
    if (!nested) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</fieldset>\r\n");



#line 82 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    } else if (!hasParent) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dd>\r\n");



#line 84 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginField(bool containsSection, HtmlString labelHtml, HtmlString elementHtml, HtmlString errorHtml, bool isValid = true, IHtmlString hint = null, string tip = null, bool hideTip = true, string hintClass = null, string parentClass = null) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 87 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                                                                                                                                                        
    var classBuilder = new ClassBuilder();
    if (!isValid) {
        classBuilder.Add("invalid");
    }
    if (parentClass != null) {
        classBuilder.Add(parentClass);
    }
    var cssClass = new HtmlString(string.IsNullOrEmpty(classBuilder.ToString()) ? "" : "class=\"" + classBuilder.ToString() + "\"");
    var tipClass = hideTip ? "" : "plain";
    if (labelHtml != null)
    {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <dt ");



#line 99 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cssClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">");



#line 99 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, labelHtml);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dt>\r\n");



#line 100 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<dd ");



#line 101 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cssClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, ">\r\n");



#line 102 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    if (hint != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <p class=\"hint ");



#line 103 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, hintClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 103 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, hint);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 104 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }
    
#line default
#line hidden


#line 105 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, errorHtml);

#line default
#line hidden


#line 105 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
              
#line default
#line hidden


#line 105 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, elementHtml);

#line default
#line hidden


#line 105 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                          
    if (tip != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <span class=\"tip ");



#line 107 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, tipClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 107 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, tip);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 108 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }
    if (!containsSection) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dd>\r\n");



#line 111 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndField() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 114 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</dd>\r\n");



#line 116 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult ErrorHtml(string errors) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 118 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                  

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <p class=\"error_text\">");



#line 119 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, errors);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</p>\r\n");



#line 120 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Footer(string area = null, string id = null, string date = null) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 122 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                          

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul class=\"footer\">\r\n");



#line 124 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     if (area != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li class=\"segment owner_area\">");



#line 125 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, area);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 126 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden



#line 127 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     if (id != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li class=\"segment id\">");



#line 128 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 129 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden



#line 130 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     if (date != null) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <li class=\"segment date\">");



#line 131 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, date);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</li>\r\n");



#line 132 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ul>\r\n");



#line 134 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 136 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                           

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"navigation\">\r\n");



#line 138 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndNavigation() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 140 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                         

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 142 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Submit(string value, string id = null, string classes = null, string name = null, bool reset = false) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 144 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                               
    var type = reset ? "reset" : "submit";
    name = String.IsNullOrEmpty(name) ? id : name;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<input type=\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, type);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                          if (classes != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " class=\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                   WebViewPage.WriteTo(@__razor_helper_writer, classes);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                              }
#line default
#line hidden



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                if (name != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " name=\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                     WebViewPage.WriteTo(@__razor_helper_writer, name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                             }
#line default
#line hidden



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                               if (id != null) {
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " id=\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                                                                      }
#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " value=\"");



#line 147 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                                    WebViewPage.WriteTo(@__razor_helper_writer, value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 148 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginMessage(string messageType, string heading) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 150 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                          
    var messageClass = messageType + "_message";

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"");



#line 152 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, messageClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        <h2>");



#line 153 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, heading);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h2>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<div class=\"message\">\r\n");



#line 155 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndMessage() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 157 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                      

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</div>\r\n");



#line 160 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BeginInputList(string type) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 162 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                     

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<ul class=\"");



#line 163 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, type);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n");



#line 164 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult EndInputList() {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 166 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                        

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        ");

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</ul>\r\n");



#line 168 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult InputListItem(string type, string name, string value, string label, bool selected = false) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 170 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                    

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <li>\r\n");



#line 172 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                  var id = name.Replace(".", "_") + value;

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <input type=\"");



#line 173 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, type);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" name=\"");



#line 173 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, name);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" id=\"");



#line 173 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
          WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 173 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                       WebViewPage.WriteTo(@__razor_helper_writer, value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" ");



#line 173 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                 WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(selected ? "checked=\"checked\"" : ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " />\r\n                <label for=\"");



#line 174 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 174 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, label);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label>\r\n            </li>\r\n");



#line 176 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BooleanRadio(string id, bool value, string falseLabel, string trueLabel) 
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 179 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul class=\"radio\">\r\n        <li><input type=\"radio\" id=\"");



#line 181 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "Yes\" name=\"");



#line 181 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
         WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" value=\"true\"");



#line 181 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                           WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(value ? " checked=\"checked\"" : ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " /> <label for=\"");



#line 181 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                 WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "Yes\">");



#line 181 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                          WebViewPage.WriteTo(@__razor_helper_writer, trueLabel);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label></li>\r\n        <li><input type=\"radio\" id=\"");



#line 182 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "No\" name=\"");



#line 182 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" value=\"false\"");



#line 182 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                           WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(!value ? " checked=\"checked\"" : ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " /> <label for=\"");



#line 182 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                  WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "No\">");



#line 182 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                          WebViewPage.WriteTo(@__razor_helper_writer, falseLabel);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label></li>\r\n    </ul>\r\n");



#line 184 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult BooleanRadioNullable(string id, bool? value, string falseLabel, string trueLabel) 
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 187 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul class=\"radio\">\r\n        <li><input type=\"radio\" id=\"");



#line 189 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "Yes\" name=\"");



#line 189 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
         WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" value=\"true\"");



#line 189 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                           WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(value == true ? " checked=\"checked\"" : ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " /> <label for=\"");



#line 189 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                         WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "Yes\">");



#line 189 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                  WebViewPage.WriteTo(@__razor_helper_writer, trueLabel);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label></li>\r\n        <li><input type=\"radio\" id=\"");



#line 190 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "No\" name=\"");



#line 190 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
        WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" value=\"false\"");



#line 190 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                           WebViewPage.WriteTo(@__razor_helper_writer, new HtmlString(value == false ? " checked=\"checked\"" : ""));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, " /> <label for=\"");



#line 190 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                          WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "No\">");



#line 190 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                  WebViewPage.WriteTo(@__razor_helper_writer, falseLabel);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</label></li>\r\n    </ul>\r\n");



#line 192 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult Grid(string id, SelectList choices, SelectList prompts, Grid<string> values, string label, string summary, bool readOnly = false) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 196 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                                                                                           
    var cellClass = readOnly ? "readonlyTd" : "textTd";

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <table summary=\"");



#line 198 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, summary);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" id=\"");



#line 198 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, id);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">\r\n        <tr>\r\n            <td>&nbsp;</td>\r\n");



#line 201 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
             foreach(var choice in choices) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <th scope=\"col\">");



#line 202 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, choice.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</th>\r\n");



#line 203 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
            }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "        </tr>\r\n");



#line 205 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
         foreach(var prompt in prompts) {
            var printRow = !readOnly
                || !string.IsNullOrWhiteSpace(prompt.Text)
                || choices.Any(choice => !string.IsNullOrWhiteSpace(values.Cell(prompt.Value, choice.Value)));
            if (printRow) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                <tr>\r\n                    <th scope=\"row\">");



#line 211 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, prompt.Text);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</th>\r\n");



#line 212 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                     foreach(var choice in choices) {
                        var cellId = string.Format("{0}.{1}.{2}", id, prompt.Value, choice.Value);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        <td class=\"");



#line 214 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, cellClass);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\">");



#line 214 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, new MvcHtmlString(readOnly ? "" : "<label>"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "<span class=\"reader\">");



#line 214 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                         WebViewPage.WriteTo(@__razor_helper_writer, label.Replace("%prompt%", prompt.Text).Replace("%choice%", choice.Text));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 215 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                         if (readOnly)
                        {
                            
#line default
#line hidden


#line 217 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, values.Cell(prompt.Value, choice.Value));

#line default
#line hidden


#line 217 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                                    
                        }
                        else
                        {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                            <input type=\"text\" id=\"");



#line 221 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
         WebViewPage.WriteTo(@__razor_helper_writer, cellId.Replace(".", "_"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" name=\"");



#line 221 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                           WebViewPage.WriteTo(@__razor_helper_writer, cellId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" value=\"");



#line 221 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                                                           WebViewPage.WriteTo(@__razor_helper_writer, values.Cell(prompt.Value, choice.Value));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 222 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                        ");



#line 223 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, new MvcHtmlString(readOnly ? "" : "</label>"));

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</td>\r\n");



#line 224 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
                    }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "                </tr>\r\n");



#line 226 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"
            }
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </table>\r\n");



#line 229 "..\..\FlowForms\Helpers\HelperDefinitions.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
