//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdms.Dmp.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using Urdms.Dmp.Web.Pages;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    using Curtin.Framework.Common.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_UrdmsBase.cshtml")]
    public class _Page_Views_Shared__UrdmsBase_cshtml : Urdms.Dmp.Web.Pages.BasePage<dynamic>
    {
#line hidden

        public _Page_Views_Shared__UrdmsBase_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


 if (ViewBag.Html5 != null)
{

WriteLiteral("    <!DOCTYPE html>\r\n");


}
else
{

WriteLiteral("    <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");


}


WriteLiteral("<html ");

       if (ViewBag.Html5 == null) {
WriteLiteral("xmlns=\"http://www.w3.org/1999/xhtml\"");


                                                                                    } else {
WriteLiteral("lang=\"en\"");


                                                                                                                  }
WriteLiteral(">\r\n<head>\r\n    <title>");


      Write(PageSettings.Title);


                              WriteLiteral("</title>");

                                       if (ViewBag.Html5 != null) {

WriteLiteral("    <meta charset=\"utf-8\" />");


                            }

WriteLiteral("    <meta name=\"DC.Title\" content=\"");


                              Write(PageSettings.Title);

WriteLiteral("\" />\r\n    <meta name=\"Description\" content=\"");


                                 Write(PageSettings.Description);

WriteLiteral("\" />\r\n    <meta name=\"DC.Description\" content=\"");


                                    Write(PageSettings.Description);

WriteLiteral("\" />\r\n    <meta name=\"Keywords\" content=\"");


                              Write(PageSettings.Keywords);

WriteLiteral("\" />\r\n    <meta name=\"DC.Subject\" content=\"");


                                Write(PageSettings.Keywords);

WriteLiteral("\" />\r\n");


     foreach (var classification in PageSettings.Classifications) {

WriteLiteral("    <meta name=\"Urdms.Classification\" content=\"");


                                          Write(classification.ToDescription());

WriteLiteral("\" />\r\n");


    }

WriteLiteral("    <meta name=\"revisit_after\" content=\"45\" />\r\n    <meta name=\"DC.Creator\" conte" +
"nt=\"");


                                Write(PageSettings.Creator);

WriteLiteral("\" />\r\n    <meta name=\"DC.Identifier\" content=\"");


                                   Write(Request.Url);

WriteLiteral("\" />\r\n");


     if (PageSettings.DateCreated != null) {

WriteLiteral("    <meta name=\"DC.Date\" content=\"");


                             Write(PageSettings.DateCreated.Value.ToString("yyyy-MM-dd"));

WriteLiteral("\" />\r\n");


    }


     if (PageSettings.DateModified != null) {

WriteLiteral("    <meta name=\"DC.Date.Modified\" content=\"");


                                      Write(PageSettings.DateModified.Value.ToString("yyyy-MM-dd"));

WriteLiteral("\" />\r\n");


    }

WriteLiteral("    <meta name=\"DC.Rights\" content=\"\" />\r\n    <meta name=\"DC.Format\" content=\"tex" +
"t/html\" />\r\n    <meta name=\"DC.Language\" content=\"en\" />\r\n    <script type=\"text" +
"/javascript\">\r\n    <!--\r\n        var Urdms = {Web: {basePath: \"");


                                 Write(Url.Content("~/"));

WriteLiteral("\"}};\r\n    -->\r\n    </script>\r\n\r\n    ");


Write(RenderSection("head", required: false));

WriteLiteral("\r\n");


     if (ViewBag.Scripts != null) {
        foreach (var script in ViewBag.Scripts)
        {

WriteLiteral("    <script src=\"");


            Write(Url.Content(script));

WriteLiteral("\" type=\"text/javascript\"></script>\r\n");


        }
    }


     if (ViewBag.Stylesheets != null) {
        foreach (var css in ViewBag.Stylesheets)
        {

WriteLiteral("    <link href=\"");


           Write(Url.Content(css));

WriteLiteral("\" type=\"text/css\" rel=\"stylesheet\" />\r\n");


        }
    }


WriteLiteral("</head>\r\n<body ");

       if (ViewBag.BodyClass != null) {
WriteLiteral("class=\"");


                                               Write(ViewBag.BodyClass);

WriteLiteral("\"");


                                                                              }
WriteLiteral(">\r\n    ");


Write(RenderBody());

WriteLiteral("\r\n</body>\r\n</html>");


        }
    }
}
