//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdms.Dmp.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using Urdms.Dmp.Web.Pages;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_UrdmsTemplate.cshtml")]
    public class _Page_Views_Shared__UrdmsTemplate_cshtml : Urdms.Dmp.Web.Pages.BasePage<dynamic>
    {
#line hidden

        public _Page_Views_Shared__UrdmsTemplate_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {

  
    Layout = "~/Views/Shared/_UrdmsBase.cshtml";
    var menus = PageSettings.Menu.GetMenus();


WriteLiteral("\r\n");


DefineSection("head", () => {

WriteLiteral("\r\n    ");


Write(RenderSection("head", required:false));

WriteLiteral("\r\n");


});

WriteLiteral("\r\n\r\n");


Write(Html.Partial("~/Views/Shared/_UrdmsBranding.cshtml"));

WriteLiteral("\r\n\r\n<div id=\"site_heading\">\r\n    <div class=\"page_positioning\">\r\n        <a href=" +
"\"");


            Write(Url.Content("~/"));

WriteLiteral("\">\r\n            ");


       Write(PageSettings.SiteTitle);

WriteLiteral("\r\n        </a>\r\n    </div>\r\n</div>\r\n<div id=\"top_navigation\">\r\n    <div class=\"pa" +
"ge_positioning\">\r\n");


         if (PageSettings.TopNavDisplay) {
            
       Write(Html.Partial("~/Views/Menu/_TopNav.cshtml", menus.TopNav));

                                                                      
        }

WriteLiteral("        <div class=\"clearing\">\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"p" +
"age_positioning\">\r\n");


     if (PageSettings.MenuNavDisplay || PageSettings.GlobalNavDisplay) {

WriteLiteral("        <div id=\"menu_navigation\">\r\n");


         if (PageSettings.MenuNavDisplay) {
            
       Write(Html.Partial("~/Views/Menu/_MenuNav.cshtml", menus.MenuNav));

                                                                        
        }


         if (PageSettings.GlobalNavDisplay) {

WriteLiteral("            <ul class=\"global\">\r\n                ");


           Write(Html.Partial("~/Views/Menu/_GlobalNav.cshtml"));

WriteLiteral("\r\n            </ul>\r\n");


        }


         if (User.Identity.IsAuthenticated) {

WriteLiteral("            <p style=\"text-align: center;\">\r\n                ");


           Write(Html.ActionLink("Log Off " + User.Identity.Name, "LogOff", "Auth", null, new { @class = "submitButton", @style = "float: none;" }));

WriteLiteral("\r\n            </p>\r\n");


        }

WriteLiteral("        </div>\r\n");


    }

WriteLiteral("    <a name=\"skip_to_content\" id=\"skip_to_content\"></a>\r\n    <div id=\"content\"\r\n");


     if (!PageSettings.MenuNavDisplay && !PageSettings.GlobalNavDisplay) {
        if (PageSettings.SideContentDisplay) {

WriteLiteral("            ");

WriteLiteral("class=\"no_menu\"\r\n");


        } else {

WriteLiteral("            ");

WriteLiteral("class=\"no_small no_menu\"\r\n");


        }
    } else if (!PageSettings.SideContentDisplay) {

WriteLiteral("        ");

WriteLiteral("class=\"no_small\"\r\n");


    }

WriteLiteral("    >\r\n        ");


   Write(RenderBody());

WriteLiteral("\r\n    </div>\r\n");


     if (PageSettings.SideContentDisplay) {

WriteLiteral("        <div id=\"small_content\">\r\n            ");


       Write(RenderSection("side_content", required:false));

WriteLiteral("\r\n        </div>\r\n");


    }

WriteLiteral("</div>\r\n");


Write(Html.Partial("~/Views/Shared/_UrdmsFooter.cshtml"));

WriteLiteral("\r\n\r\n\r\n");


        }
    }
}
