//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urdms.ProvisioningService.SharePoint.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.yourdomain.edu.au/_vti_bin/taxonomyclientservice.asmx")]
        public string Urdms_ProvisioningService_SharePoint_termsservice_Taxonomy_x0020_web_x0020_service {
            get {
                return ((string)(this["Urdms_ProvisioningService_SharePoint_termsservice_Taxonomy_x0020_web_x0020_servic" +
                    "e"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sharepoint.yourdomain.edu.au/_vti_bin/taxonomyclientservice.asmx")]
        public string Urdms_ProvisioningService_SharePoint_termsservice_Taxonomy_x0020_web_x0020_service1 {
            get {
                return ((string)(this["Urdms_ProvisioningService_SharePoint_termsservice_Taxonomy_x0020_web_x0020_servic" +
                    "e1"]));
            }
        }
    }
}
